language: php

php:
  - 5.4
  - 5.5

before_install:
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  # This is read only token for only public repos
  - "mkdir -p ~/.composer"
  - mv .travis.composer.config.json ~/.composer/config.json
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `test-luna`;'
  - mysql --default-character-set=utf8 test-luna < tests/structure.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
